commerce_payment.commerce_payment_gateway.plugin.korapay:
  type: commerce_payment_gateway_configuration
  mapping:
    public_key:
      type: string
      label: 'Public key'
    secret_key:
      type: string
      label: 'Secret key'
    pay_button_text:
      type: string
      label: 'Pay Button Text'